/**
 * 200 fun facts about music, musicians, and instruments.
 * Used as rotating loading messages during music generation.
 */
export const MUSIC_FACTS: string[] = [
  "Mozart composed his first piece of music at age 5.",
  "A piano has 88 keys — 52 white and 36 black.",
  "Beethoven continued composing masterpieces after going completely deaf.",
  "The world's longest concert lasted 453 hours in 2019.",
  "Vinyl records spin at exactly 33⅓ revolutions per minute.",
  "The guitar is the most popular instrument in the world.",
  "Bach had 20 children, many of whom became famous musicians.",
  "The human voice is technically the oldest musical instrument.",
  "A violin contains about 70 individual pieces of wood.",
  "The shortest song ever recorded is 1.316 seconds long.",
  "Freddie Mercury had a vocal range spanning four octaves.",
  "The didgeridoo is one of the oldest instruments, dating back 40,000 years.",
  "Music can physically affect your heart rate and blood pressure.",
  "The word 'music' comes from the Greek word 'mousike.'",
  "Jimi Hendrix was self-taught and couldn't read sheet music.",
  "A flute made from a vulture bone is 35,000 years old.",
  "The average pop song is 3 minutes and 30 seconds long.",
  "Listening to music releases dopamine in the brain.",
  "The saxophone was invented by Adolphe Sax in 1846.",
  "Cows produce more milk when listening to slow music.",
  "The longest-running musical is The Phantom of the Opera.",
  "A harp has 47 strings and 7 foot pedals.",
  "The term 'jazz' first appeared in print in 1913.",
  "Spotify has over 100 million songs in its library.",
  "Birds can recognize and remember specific melodies.",
  "The theremin is played without any physical contact.",
  "Chopin composed mostly for solo piano.",
  "The first commercial CD pressed was ABBA's 'The Visitors.'",
  "Sound travels about 4 times faster in water than in air.",
  "A grand piano can weigh up to 1,200 pounds.",
  "The first known musical notation dates back to 1400 BCE.",
  "Elvis Presley never wrote any of his own songs.",
  "The triangle is one of the hardest orchestral instruments to master.",
  "Music therapy is a recognized clinical practice worldwide.",
  "The world's largest orchestra had 8,097 musicians.",
  "Vivaldi was nicknamed 'The Red Priest' for his red hair.",
  "A standard guitar has 6 strings, but some have up to 18.",
  "The first MP3 player was released in 1998.",
  "Paganini was so skilled that people thought he made a deal with the devil.",
  "The pipe organ is the largest musical instrument.",
  "Babies can distinguish musical rhythm before they can walk.",
  "The ukulele means 'jumping flea' in Hawaiian.",
  "Tchaikovsky's 1812 Overture calls for actual cannons.",
  "A drumstick hits a snare drum at about 40 mph.",
  "The Beatles hold the record for most number-one hits.",
  "Whale songs can travel thousands of miles through the ocean.",
  "The metronome was patented in 1815 by Johann Maelzel.",
  "Stradivarius violins are worth millions due to their unique sound.",
  "The first electric guitar was made in 1931.",
  "Plants grow faster when exposed to classical music.",
  "A church organ can have over 10,000 pipes.",
  "The harmonica is the world's best-selling instrument.",
  "Rachmaninoff had hands that could span 12 piano keys.",
  "The first song played in space was 'Jingle Bells' in 1965.",
  "A cello is tuned to C-G-D-A, from lowest to highest.",
  "Music can help improve memory and cognitive function.",
  "The banjo originated from instruments brought from West Africa.",
  "Debussy was a pioneer of musical impressionism.",
  "The loudest sound ever recorded was the eruption of Krakatoa.",
  "A concert pitch A is standardized at 440 Hz.",
  "The bagpipes were originally made from animal bladders.",
  "Handel composed 'Messiah' in just 24 days.",
  "The first music video on MTV was 'Video Killed the Radio Star.'",
  "An octave doubles the frequency of a note.",
  "The sitar has 18 to 21 strings.",
  "Liszt was the first musician to perform a solo concert.",
  "Sound cannot travel through a vacuum.",
  "The French horn has 12 feet of tubing coiled up.",
  "Earworms are songs that get stuck in your head involuntarily.",
  "The oldest known song is the 'Hurrian Hymn No. 6.'",
  "A tuba player uses about 14.4 liters of air per minute.",
  "Synesthesia lets some people 'see' music as colors.",
  "The accordion was invented in Vienna in 1829.",
  "Bob Dylan won the Nobel Prize in Literature in 2016.",
  "A violin bow contains 150-200 horsehair strands.",
  "The pentatonic scale is found in music across all cultures.",
  "Noise-canceling headphones were invented for airplane pilots.",
  "The first opera was performed in Florence around 1597.",
  "A bass drum can produce sounds as low as 20 Hz.",
  "Schubert composed over 600 songs in his short life.",
  "The marimba is the national instrument of Guatemala.",
  "Perfect pitch occurs in about 1 in 10,000 people.",
  "The first Walkman was released by Sony in 1979.",
  "Gregorian chants date back to the 9th century.",
  "A clarinet has about 17 keys.",
  "The blues originated in the Deep South of the United States.",
  "Ravel's 'Boléro' uses the same melody repeated 18 times.",
  "The world's most expensive instrument sold for $45 million.",
  "Singing in a group releases oxytocin, the bonding hormone.",
  "The oboe is used to tune the entire orchestra.",
  "Tempo markings like 'allegro' and 'adagio' are Italian words.",
  "A steel drum is made from an oil barrel.",
  "The first Grammy Awards were held in 1959.",
  "Pythagoras discovered the mathematical ratios behind musical intervals.",
  "The xylophone name means 'wood sound' in Greek.",
  "Beethoven's Fifth Symphony opens with the most famous four notes in music.",
  "A trumpet has only three valves but can play all chromatic notes.",
  "The Nashville Number System uses numbers instead of note names.",
  "Reggae music originated in Jamaica in the late 1960s.",
  "A double bass is the largest string instrument in an orchestra.",
  "The first synthesizer weighed over 200 pounds.",
  "Birdsong influenced composers like Messiaen and Beethoven.",
  "The kalimba, or thumb piano, originated in Africa over 3,000 years ago.",
  "Verdi and Wagner were born in the same year: 1813.",
  "A snare drum gets its buzzing sound from metal wires underneath.",
  "The word 'symphony' means 'sounding together.'",
  "Auto-Tune was originally designed for seismic data analysis.",
  "The mandolin is a member of the lute family.",
  "Shostakovich hid secret messages in his musical compositions.",
  "A piccolo is the highest-pitched instrument in an orchestra.",
  "The first known love song was written 4,000 years ago in Mesopotamia.",
  "Music activates more parts of the brain than any other stimulus.",
  "The trombone is the only brass instrument with a slide.",
  "Bossa nova means 'new trend' in Portuguese.",
  "A concert grand piano has over 12,000 individual parts.",
  "The first karaoke machine was invented in Japan in 1971.",
  "Mahler's Symphony No. 3 is the longest symphony in standard repertoire.",
  "The glass harmonica was invented by Benjamin Franklin.",
  "Fado music from Portugal is a UNESCO cultural heritage.",
  "A bassoon has over 7 feet of tubing.",
  "The first rock and roll record is debated but often cited as 1951.",
  "Choral singing synchronizes the heartbeats of choir members.",
  "The shamisen is a traditional Japanese three-stringed instrument.",
  "Brahms destroyed many of his own compositions out of perfectionism.",
  "A cymbal can vibrate for up to 30 seconds after being struck.",
  "The first public radio broadcast of music was in 1906.",
  "Gamelan is a traditional ensemble music from Indonesia.",
  "The celesta produces its bell-like sound from metal plates.",
  "Satie's 'Vexations' is meant to be played 840 times in a row.",
  "The first Stradivarius violin was made around 1666.",
  "Music tempo can influence how fast people eat.",
  "A French horn player's hand inside the bell changes the pitch.",
  "The first digital recording was made in 1979.",
  "Flamenco music originated from Andalusia in southern Spain.",
  "The contrabassoon can play notes lower than a piano's lowest key.",
  "Stevie Wonder signed with Motown Records at age 11.",
  "A church bell can weigh over 20 tons.",
  "The pentatonic scale has only five notes per octave.",
  "The first jukebox was installed in San Francisco in 1889.",
  "Prokofiev wrote 'Peter and the Wolf' to teach children about instruments.",
  "A trombone slide has seven positions.",
  "The samba originated as a Brazilian dance music form.",
  "Clara Schumann was one of the first female concert pianists.",
  "An organ pedal board is played with the feet.",
  "The first music streaming service launched in 2001.",
  "Tuvan throat singing produces two pitches simultaneously.",
  "A viola is slightly larger than a violin but has a deeper tone.",
  "The first phonograph was invented by Thomas Edison in 1877.",
  "K-pop became a global phenomenon starting in the 2010s.",
  "The cor anglais is neither English nor a horn — it's a French oboe.",
  "Gershwin's 'Rhapsody in Blue' blends jazz and classical music.",
  "A timpani drum can be tuned to specific pitches.",
  "The first music copyright law was enacted in 1710 in England.",
  "Afrobeat was pioneered by Fela Kuti in Nigeria.",
  "The hurdy-gurdy is a mechanical string instrument with a crank.",
  "Debussy once said, 'Music is the silence between the notes.'",
  "A concert hall's acoustics can take years to perfect.",
  "The first portable radio was sold in 1954.",
  "Raga is the melodic framework used in Indian classical music.",
  "A harpsichord plucks strings while a piano hammers them.",
  "The world record for fastest piano playing is 19.5 notes per second.",
  "Mariachi music originated in western Mexico in the 18th century.",
  "The English word 'chord' comes from the Latin 'chorda' meaning string.",
  "A bass clarinet is twice the length of a regular clarinet.",
  "The first Bluetooth speaker was released in 2004.",
  "Minimalist music by composers like Glass uses repetitive patterns.",
  "The erhu is a two-stringed Chinese instrument played with a bow.",
  "Strauss waltzes were once considered scandalously fast.",
  "A maracas' sound comes from seeds or beads inside a shell.",
  "The first music festival at Woodstock drew 400,000 people.",
  "Carnatic music is one of the oldest music systems in the world.",
  "The vibraphone uses rotating discs to create its vibrato effect.",
  "Elgar's 'Enigma Variations' contains a hidden melody no one has found.",
  "A djembe drum originated in West Africa around 1200 CE.",
  "The first surround sound system was developed for Disney's Fantasia.",
  "Hindustani music uses ragas associated with specific times of day.",
  "A recorder was one of the most important instruments in the Renaissance.",
  "The loudest instrument in an orchestra is the trumpet.",
  "Samba schools in Brazil can have thousands of musicians.",
  "The chromatic scale has 12 notes in Western music.",
  "A dulcimer is played by striking strings with small hammers.",
  "The first noise complaint about music was filed in ancient Rome.",
  "Gagaku is the oldest form of Japanese classical music.",
  "A French horn can play both brass and woodwind ensemble parts.",
  "The first electric organ was built in 1934.",
  "Sufi music uses repetitive rhythms to induce a meditative state.",
  "A lyre was the most popular instrument in ancient Greece.",
  "The first music app for smartphones launched in 2008.",
  "West African griot musicians are living libraries of oral history.",
  "A pedal steel guitar can bend notes smoothly using foot pedals.",
  "The first surround sound movie soundtrack was in 1940.",
  "Klezmer music originated from Eastern European Jewish traditions.",
  "The world's smallest playable violin is just one inch long.",
  "Aboriginal Australians have used music for over 60,000 years.",
  "A glockenspiel uses metal bars while a xylophone uses wooden ones.",
  "The first auto-tuned hit song was Cher's 'Believe' in 1998.",
  "Qawwali is a form of Sufi devotional music from South Asia.",
  "Every snowflake vibrates at a unique frequency when it lands.",
  "The first wireless headphones were invented in the 1960s.",
  "Tango music originated in the neighborhoods of Buenos Aires.",
  "A pipe organ's largest pipes can be 32 feet tall.",
  "The first album to sell one million copies was by Enrico Caruso.",
];
